spring.application.name=cabonerf-be

# Database settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# RabbitMQ settings
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

# Secret keys
app.access_token_secret_key=${ACCESS_TOKEN_SECRET_KEY}
app.refresh_token_secret_key=${REFRESH_TOKEN_SECRET_KEY}
app.email_verify_token_secret_key=${EMAIL_VERIFY_TOKEN_SECRET_KEY}
app.forgot_password_token_secret_key=${FORGOT_PASSWORD_SECRET_KEY}

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#deployed db
#spring.datasource.url=jdbc:postgresql://autorack.proxy.rlwy.net:13516/railway
#spring.datasource.username=postgres
#spring.datasource.password=kijONhfaKmEQcjfUdlfaudnXYkkHWpYZ

## local db
#spring.datasource.url=jdbc:postgresql://localhost:2345/cabonerf
#spring.datasource.username=postgres
#spring.datasource.password=12345

#aws db
#spring.datasource.url=jdbc:postgresql://capstone-project.cnkk8sqc87aw.us-east-2.rds.amazonaws.com:5432/cabonerf
#spring.datasource.username=postgres
#spring.datasource.password=kijONhfaKmEQcjfUdlfaudnXYkkHWpYZ

# local rabbitmq
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=cabonerf
#spring.rabbitmq.password=cabonerfpass

# local secret
#app.access_token_secret_key = 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#app.refresh_token_secret_key = QkNGR1JLUFpWM1lZQ2ZYMkZUUldOTkZPTURHTkxTSlZKVEZNSUJNWkFGQQ==
#app.email_verify_token_secret_key = A7B8C9D6E2F123456789ABCD345EF6789F0123456789ABCDEF34567890ABCDEF
#app.forgot_password_token_secret_key = D4E5F6A7B8C9D123456789ABCDEF123456789ABCD1234567890ABCDEFFEDCBA9



