name: Cabonerf App to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: cabonerf-be
          path: ${{ github.workspace }} /target/*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from github job
        uses: actions/download-artifact@v3
        with:
          name: cabonerf-be
      - name: Deploy to Azure App Service
        uses: azure/webapp-deploy@v2
        with:
          app-name: cabonerf
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: '*.jar'